### ISSUE TITLE
ラムダをやむなく入れ子にした部分のリファクタリング

### ISSUE THREAD

**Issue by Clpsplug** [Clpsplug/CCADXKawazLogo#2]
Description given in the source code

**Comment by giginet** [comment]
`Action`は内部状態も保持しているため、複数のアクションキューで使い回すことができない
1. ラムダを定義する
2. ラムダをコピーする
3. それらを使って別々の`CallFunc`アクションを作る

ってやると上手く行く気がする（未確認）

**Comment by Clpsplug** [comment]
[こう](http://stackoverflow.com/questions/30501924/how-can-i-reuse-cocos2daction)すればよかった！なんで気づかなかったんだ
thx to [Andrey Chernukha](http://stackoverflow.com/users/994107/andrey-chernukha?tab=profile) for help
